In [ ]:
#Problem One: Array Creation
#Initialize an empty array with size 2X2.

import numpy as np
emptyarr = np.empty((2, 2))
emptyarr


array([[1., 1.],
       [1., 1.]])

In [ ]:
#Initialize an all one array with size 4X2.

import numpy as np
onearr = np.ones((4, 2))
onearr


array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
#Return a new array of given shape and type, filled with fill value.

import numpy as np
fullarr = np.full((4, 2), 7)
fullarr



array([[7, 7],
       [7, 7],
       [7, 7],
       [7, 7]])

In [ ]:
#Return a new array of zeros with same shape and type as a given array.

import numpy as np
a = np.array([[1, 2, 3],[4, 5, 6]])
arr = np.zeros_like(a)
arr


array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
#Return a new array of ones with same shape and type as a given array.

import numpy as np
a = np.array([[1, 2, 3],[2, 4, 9]])
arr = np.ones_like(a)
arr


array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
#For an existing list new_list = [1,2,3,4] convert to an numpy array.

import numpy as np
new_list = [1, 2, 3, 4]
arr = np.array(new_list)
arr


array([1, 2, 3, 4])

In [ ]:
#Problem Two: Array Manipulation: Numerical Ranges and Array indexing:
#Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

import numpy as np
arr = np.arange(10, 50)
arr


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
#Create a 3X3 matrix with values ranging from 0 to 8.
#{Hint:look for np.reshape()}

import numpy as np
arr = np.arange(0,9).reshape(3, 3)
arr


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
#Create a 3X3 identity matrix.{Hint:np.eye()}

import numpy as np
identityMatrix = np.eye(3, dtype=int)
identityMatrix


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
#Create a random array of size 30 and find the mean of the array.
#{Hint:check for np.random.random() and array.mean() function}

import numpy as np
arr = np.random.random(30)
mean = arr.mean()
arr,mean


(array([0.01759253, 0.98859217, 0.48268333, 0.17014701, 0.73592412,
        0.6625219 , 0.35370817, 0.35050465, 0.35184614, 0.95675123,
        0.17835608, 0.28529975, 0.41043979, 0.85346159, 0.58753398,
        0.36129421, 0.03362596, 0.29754021, 0.49972419, 0.53934462,
        0.98657348, 0.17570703, 0.72186809, 0.55103892, 0.98045614,
        0.02813085, 0.7897421 , 0.38089355, 0.4300276 , 0.2793411 ]),
 np.float64(0.4813556832278774))

In [ ]:
#Create 10X10 array with random values and find the min and max values.

import numpy as np
arr = np.random.random((10, 10))
minValue = arr.min()
maxValue = arr.max()
arr, minValue, maxValue


(array([[0.12176579, 0.15450292, 0.40353893, 0.56799532, 0.50900547,
         0.71069518, 0.87130812, 0.42846719, 0.13933927, 0.94536103],
        [0.22464326, 0.69062554, 0.76682275, 0.15209184, 0.07881184,
         0.82621663, 0.89654989, 0.76934763, 0.32604484, 0.73658006],
        [0.5330217 , 0.11469148, 0.88083456, 0.86950374, 0.38429036,
         0.85531626, 0.14466823, 0.05019151, 0.88999142, 0.35930859],
        [0.87400144, 0.63288475, 0.07062755, 0.0438995 , 0.03097042,
         0.0127061 , 0.24955847, 0.99889853, 0.07215139, 0.15022712],
        [0.31205776, 0.73350276, 0.86701721, 0.69517782, 0.35695446,
         0.9602308 , 0.2173019 , 0.88052592, 0.08615723, 0.83994838],
        [0.41317828, 0.31202751, 0.38390701, 0.26020876, 0.92797269,
         0.5137368 , 0.82510769, 0.5535609 , 0.97267543, 0.70393608],
        [0.63307491, 0.95433992, 0.49550128, 0.79344561, 0.81699403,
         0.10401848, 0.44171347, 0.41119247, 0.41689795, 0.5111146 ],
        [0.82299628, 0.6178

In [ ]:
#Create a zero array of size 10 and replace 5th element with 1.

import numpy as np
arr = np.zeros(10, dtype=int)
arr[4] = 1
arr


array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [ ]:
#Reverse an array arr = [1,2,0,0,4,0].

import numpy as np
arr = np.array([1, 2, 0, 0, 4, 0])
reversedArray = arr[::-1]
reversedArray


array([0, 4, 0, 0, 2, 1])

In [ ]:
#Create a 2d array with 1 on border and 0 inside.

import numpy as np
array = np.ones((5, 5), dtype=int)
array[1:-1, 1:-1] = 0
print(array)



[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
#Create a 8X8 matrix and fill it with a checkerboard pattern.

import numpy as np
checkerboard_pattern = np.zeros((8, 8), dtype=int)
checkerboard_pattern[1::2, ::2] = 1
checkerboard_pattern[::2, 1::2] = 1
print(checkerboard_pattern)



[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [8]:
#Problem 3: Array Operations:
#For the following arrays:
# x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
# v = np.array([9,10]) and w = np.array([11,12]);
#Add the two array.

import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
addArray1 = x + y
addArray2 =v + w
addArray1, addArray2


(array([[ 6,  8],
        [10, 13]]),
 array([20, 22]))

In [9]:
#Subtract the two array.

import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
subArray1 = x - y
subArray2= v - w
subArray1, subArray2


(array([[-4, -4],
        [-4, -3]]),
 array([-2, -2]))

In [12]:
#Multiply the array with any integers of your choice.

import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
mul_x = x * 3
mul_y = y * 3
mul_v = v * 3
mul_w = w * 3
mul_x, mul_y, mul_v, mul_w


(array([[ 3,  6],
        [ 9, 15]]),
 array([[15, 18],
        [21, 24]]),
 array([27, 30]),
 array([33, 36]))

In [13]:
#Find the square of each element of the array.

import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
sq_x = x ** 2
sq_y = y ** 2
sq_v = v ** 2
sq_w = w ** 2
sq_x, sq_y, sq_v, sq_w


(array([[ 1,  4],
        [ 9, 25]]),
 array([[25, 36],
        [49, 64]]),
 array([ 81, 100]),
 array([121, 144]))

In [16]:
#Find the dot product between: v(and)w ; x(and)v ; x(and)y.

import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
dot_vw= np.dot(v,w)
dot_xv= np.dot(x,v)
dot_xy= np.dot(x,y)
dot_vw, dot_xv, dot_xy

(np.int64(219),
 array([29, 77]),
 array([[19, 22],
        [50, 58]]))

In [18]:
#Concatenate x(and)y along row and Concatenate v(and)w along column.
#{Hint:try np.concatenate() or np.vstack() functions.

import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
xy_row = np.concatenate((x, y), axis=0)
vw_col = np.concatenate((v.reshape(2,1), w.reshape(2,1)), axis=1)
xy_row, vw_col


(array([[1, 2],
        [3, 5],
        [5, 6],
        [7, 8]]),
 array([[ 9, 11],
        [10, 12]]))

In [19]:
#Concatenate x(and)v; if you get an error, observe and explain why did-
# -you get the error?

import numpy as np
x = np.array([[1,2],[3,5]])
v = np.array([9,10])
np.concatenate((x, v))
#x has shape (2,2) (2-dimesnion)
#v has shape (2,) (1-dimensional)
#NumPy requires arrays to have the same number of dimensions when concatenating along a given axis.



ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [21]:
#Problem - 4: Matrix Operations:
#For the following arrays:
# A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
#Prove following with Numpy:

import numpy as np
A = np.array([[3,4], [7,8]])
B = np.array([[5,3], [2,1]])

#1. Prove A.A−1 = I.
A_inv = np.linalg.inv(A)
result = np.dot(A, A_inv)
result_int = np.round(result).astype(int)

print(f"A * A^-1 = \n {result_int}")
print("\n")


#2. Prove AB ̸= BA.
result_ab= np.dot(A, B)
result_ba= np.dot(B, A)

print(f"AB = \n {result_ab}")
print(f"BA = \n {result_ba}")
print("Since the value of AB and BA are different, therefore AB ̸= BA.")
print("\n")

#3. Prove (AB)T = BTAT

AB_T = np.transpose(np.dot(A, B))
BT_AT = np.dot(np.transpose(B), np.transpose(A))

print("(AB)^T =\n", AB_T)
print("B^T A^T =\n", BT_AT)
print("Since (AB)^T and B^TA^T are same therefore (AB)^T = B^TA^T ")


A * A^-1 = 
 [[1 0]
 [0 1]]


AB = 
 [[23 13]
 [51 29]]
BA = 
 [[36 44]
 [13 16]]
Since the value of AB and BA are different, therefore AB ̸= BA.


(AB)^T =
 [[23 51]
 [13 29]]
B^T A^T =
 [[23 51]
 [13 29]]
Since (AB)^T and B^TA^T are same therefore (AB)^T = B^TA^T 


In [22]:
#Solve the following system of Linear equation using Inverse Methods.

# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9
#{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

import numpy as np
A_eq = np.array([[2, -3, 1],
                 [1, -1, 2],
                 [3, 1, -1]])

B_eq = np.array([-1, -3, 9])

x = np.linalg.solve(A_eq, B_eq).astype(int)

print("This is using only np.linalg only ")
print(x)
print("\n")

#Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function of Numpy}


a_inv = np.linalg.inv(A_eq)
x = np.dot(a_inv, B_eq).astype(int)
print("This is using np.linagl.inv function ")
print(x)

This is using only np.linalg only 
[ 2  1 -2]


This is using np.linagl.inv function 
[ 2  1 -2]
